### ISSUE TITLE
Unifikacja wszystkich przycisków w jeden komponent

### ISSUE THREAD

**Issue by tchojnacki** [CodersCamp2021-HK/CodersCamp2021.Project.JavaScript#44]
Połączenie następujących przycisków w jeden komponent (z różnymi wariantami):
- "Start" i "Ranking" (`MenuButton`)
- "Kategoria" i "Poziom" (`GameTypeButton`)
- "Quiz" (niezrobiony)

**Comment by KamilDudek** [comment]
Robię ten przycisk do Quizu to już przy okazji połącze to wszystko w całość.
